### ISSUE TITLE
How can this work concurrently?

### ISSUE THREAD

**Issue by raboof** [eirslett/sbt-slf4j#2]
You're suggesting assigning a value to `StaticLoggerBinding.sbtLogging` for each task, but tasks can be run in parallel, so this doesn't make a whole lot of sense, right? Can you clarify?

**Comment by raboof** [comment]
Ah, you assume `SbtLoggerFactory.getLogger` will be called quickly after setting `StaticLoggerBinding.sbtLogging`. Tricky, but hard to think of alternatives...

**Comment by eirslett** [comment]
Yup, as I have understood it, sbt can (at least in theory) use separate loggers for separate tasks that run in parallel, while SLF4J is based on using one global logging implementation. There's a mismatch there.
In practice, it hasn't turned out to be a problem.
